### ISSUE TITLE
Readme says for windows users to use a release, but there are no releases in the releases section. 

### ISSUE THREAD

**Issue by anakaine** [BDisp/unlocker#18]

**Comment by BDisp** [comment]
Now is inside the `Tags` https://github.com/BDisp/unlocker/tags

**Comment by BDisp** [comment]
It's already in the `Releases`. See https://github.com/BDisp/unlocker/releases.

**Comment by ioc2e3** [comment]
> It's already in the `Releases`. See https://github.com/BDisp/unlocker/releases.

Excuse me ...

Can it be the same as here ( https://github.com/DrDonk/unlocker/releases ) ?
Provide ( .zip file )( .tgz file ) ...

Can it be the same as here ( https://github.com/paolo-projects/unlocker/releases ) ?
Provide ( .zip file )( .tgz file ) ...

Can it be the same as here ( https://github.com/paolo-projects/auto-unlocker/releases ) ?
Provide ( .zip file ) ...

.

**Comment by BDisp** [comment]
Please, give a reason to do more separate compact files for this repo. The end user doesn't have the need to compile it for being to run it into Windows, because it already provide executable files (.exe) or into Linux, because normally the OS already have python installed. The end user only have to run the correct `win-*.cmd` file in Windows or the correct `lnx-*.sh` file in Linux. But I may missing something that you probable already know and want to share.
