### ISSUE TITLE
No internet connection when upgraded to VMWare Workstation Pro 16.2.2

### ISSUE THREAD

**Issue by gquiring** [BDisp/unlocker#20]
I reran the script as admin for Win 10.  (killed all the processes first).  My VM is Monterey.  It loads ok but no network connection.

**Comment by BDisp** [comment]
It isn't enough only kill all the process, because if you rerun the `unlocker` it will patch on the patched files and that will end up with invalid patch files. The best procedure is to run the batch uninstaller, which will replace the patched files with the originals (in case you didn't deleted the backup folder) and then run the installer.
The `Monterey` is still in beta and I don't installed it yet.

**Comment by humanspida** [comment]
I can confirm that if you have your VM network settings for Monterey set to NAT then it won't work "out-of-the-box"
You can change this setting to BRIDGED, which is a direct connection to the physical network
This can be done with the VM powered on and in use, no worries

That ought to give you access to the internet though... Obviously make sure you have adequate security in place if you plan to leave it set to this mode long term. If it's not necessary to have the internet connected to the Monterey VM at all times - then just turn it on, do what you need to and turn it off again.

Edit: 
Not exactly ideal... but it'll do the job and you should be fine if you use half a brain cell for your internet stuff

**Comment by gquiring** [comment]
> I can confirm that if you have your VM network settings for Monterey set to NAT then it won't work "out-of-the-box" You can change this setting to BRIDGED, which is a direct connection to the physical network This can be done with the VM powered on and in use, no worries
> 
> That ought to give you access to the internet though... Obviously make sure you have adequate security in place if you plan to leave it set to this mode long term. If it's not necessary to have the internet connected to the Monterey VM at all times - then just turn it on, do what you need to and turn it off again.
> 
> Edit: Not exactly ideal... but it'll do the job and you should be fine if you use half a brain cell for your internet stuff

It is NAT but worked with 16.2.1.  Why would the upgrade break that?

**Comment by humanspida** [comment]
I haven't actually read the changelog for either 16.2.1 or 16.2.2 so I couldn't tell you what changes were made, Even if I had read them - I probably couldn't tell you what precisely it was that might have caused the issue because I'm not that well versed in programming, etc.

**Comment by BDisp** [comment]
I think whatever was changed in the 16.2.2 version, nothing can be done with the `unlocker`, because it only unlocks the `macOS` options.

**Comment by humanspida** [comment]
I would say file a bug report with VMware but seeing as it's an unofficial / unsupported mod for Windows VMware Workstation & Player to enable a feature that's only supposed to be present on Apple computers running VMware I think - they'll probably do nothing about it as long as everything else that's meant to be part of the Windows version works fine.

**Comment by mkitchingh** [comment]
I can confirm I do not experience this issue. Confirmed on multiple devices. See pic. As others said as well though, this issue wouldn't be an Unlocker problem. 

![image](https://user-images.githubusercontent.com/25916510/150607666-ef9373f2-7500-4710-ad46-dc04baeb9d9f.png)

**Comment by humanspida** [comment]
Interesting, I wonder what it is that's affecting our systems and preventing NAT mode from working for us

**Comment by BDisp** [comment]
I only maintain this because there are people who needs this for some disease causes. But personally I prefer using the `VirtualBox`, much faster e without great freezes. `VMware` freezes so much and a lot of times it locks and I have to kill it's process. I only use it to test the unlocker, nothing more else.

**Comment by mkitchingh** [comment]
> I only maintain this because there are people who needs this for some disease causes.

Thank you. More than I can express.

**Comment by humanspida** [comment]
Not all heros wear capes...
Or maybe BDisp does have a cape 😁

**Comment by humanspida** [comment]
OK, so I know this has been closed but I sorted my own NAT conectivity issue.
For anyone else having internet connection issues with VM network set to NAT after either upgrading or installing VMware Workstation or Player 16.2.2 and applying the unlocker...

Did you check the services ?? 
Remember when you used the installer and made sure there were no VMware processes running, perhaps by killing them?

Open the RUN command window and input the following:
services.msc

Hit Enter or click OK
Now sort the services by name - descending and take a short scroll down to the V section

Set the following to Automatic if they aren't already and manually start them if they arent running:

VMware USB Arbitration Service
VMware NAT Service
VMware DHCP Service
VMware Authorization Service

You should now be good to go 😁 internet returned to normal for your VMs

**Comment by BDisp** [comment]
For sure it was work of the CCleaner. I prefer handle the register by my self.

**Comment by humanspida** [comment]
Nah, it wasn't CCleaner, although I did do a clean up with it I didn't attack the registry for a clean.
I did however kill some processes with the task manager before applying the unlocker, had to do it a few times I remember now because they kept coming back... so obviously Windows got the point and left them off along with the associated services - then having not had any reason to reboot the machine, the services, although set to automatic already, hadn't been restarted because no reboot to trigger it.
A reboot may not be enough for some people if those services have somehow been flagged as anything other than Automatic though
