### ISSUE TITLE
keyboard mouse do not work in mac catalina - Vmware workstation 15.5 on Ubuntu 18.04 LTS x64

### ISSUE THREAD

**Issue by shkpk** [BDisp/unlocker#4]
I'm using Vmware workstation 15.5 on Ubuntu 18.04 LTS x64, and trying to install Mac Catalina 10.15.1 via iso. Somehow on first pop up of selecting region, I cant move mouse or keyboard.
Any idea?

**Comment by BDisp** [comment]
I currently don't have `VMWare `installed so I can't test it. If you have already installed the `VM's Tools` try to edit the `.bashrc` file and type "`export TERM=xterm-1006`" and save it. You can use `vi` or `nano `to edit and restart. If it doesn't work, I don't know how to help you because I'm not thinking about working on it for now.

**Comment by shkpk** [comment]
> I currently don't have `VMWare `installed so I can't test it. If you have already installed the `VM's Tools` try to edit the `.bashrc` file and type "`export TERM=xterm-1006`" and save it. You can use `vi` or `nano `to edit and restart. If it doesn't work, I don't know how to help you because I'm not thinking about working on it for now.

ok no problem. I'll figure it out.
