### ISSUE TITLE
Failed to Download VIRUS detected.

### ISSUE THREAD

**Issue by NitishAndola** [BDisp/unlocker#41]
![Screenshot 2024-12-23 181424](https://github.com/user-attachments/assets/3e866bda-2217-4477-83ac-9b958cab37af)

**Comment by BDisp** [comment]
For sure that may be a false positive. Which anti-virus you're are using?

**Comment by NitishAndola** [comment]
I’m not using any third-party antivirus, just Windows Defender. Chrome is blocking the download of the zip file.

**Comment by BDisp** [comment]
I downloaded the file now using Chrome and it didn't report any virus. Please try download with other browser as well.

**Comment by NitishAndola** [comment]
I tried downloading the file again, this time using Mozilla Firefox. However, Windows Defender is still blocking it, indicating that the file contains **Trojan:Win32/Wacatac.B!ml**

Here’s the screenshot of the alert:
![image](https://github.com/user-attachments/assets/8f22cc2b-6fea-4eda-a8e4-7505436757ae)

**Comment by BDisp** [comment]
If you search for `Wacatac.B!ml` you'll see that's a false positive. If you want to have sure that all is fine you can scan with https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download. I think it's due to the exe files, which are secure but browsers don't like them. Even compile a simple `c++` project Windows Defender complain with the exe generated and we need to add the development folders to the ignore folders scan list.

**Comment by BDisp** [comment]
Closing this because it's a false positive virus since a very long time ago.
