### ISSUE TITLE
Big Sur?

### ISSUE THREAD

**Issue by mkitchingh** [BDisp/unlocker#5]
Hey, I was one of the people that worked on the effort to get things working with Catalina. Do you plan to try to have an updated version to work with Big Sur? It seems like some people are having some success, although these installation instructions are a little messy. 
https://www.wikigain.com/install-macos-big-sur-on-vmware-windows-pc/
I maintain this site:
https://macosvmware.tech.blog/
which was created to support users of this medical software 
https://loopkit.github.io/loopdocs/
that can't afford a Mac.

**Comment by BDisp** [comment]
Hi, yes I remember. I've been out of mac a long time and I never used the vmware software anymore. I've no time for now sorry. I'm only on Windows and a little of Linux.

**Comment by BDisp** [comment]
@mkitchingh I ended up reinstalling VMware again, because now it has support to live side by side with Hiper-V. I was able to install Big Sur with the latest VMware® Workstation 15 Pro, version 15.5.6 build-16341506 and the current version of the unlocker 3.0.3. It takes a long time to install with the Apple logo looking static, but it ended up being installed. But we are talking about the beta version of Big Sur and even the final release version can be difficult. So I'm only going to test again when the release version comes out. I just couldn't download the beta version with my AppleID because that option didn't appear, so I had to use the download from the link you referenced.

![big-sur](https://user-images.githubusercontent.com/13117724/91492144-0b03b500-e8ad-11ea-9b8c-ff6fe62558b4.png)
